Don't fail out if script doesn't return ok; don't want regression in case script has a bug

diff --git a/.github/actions/wait-for-as-server-to-start/action.yml b/.github/actions/wait-for-as-server-to-start/action.yml
--- a/.github/actions/wait-for-as-server-to-start/action.yml
+++ b/.github/actions/wait-for-as-server-to-start/action.yml
@@ -16,8 +16,10 @@ runs:
     shell: bash
 
   # Composite actions doesn't support step-level timeout-minutes
-  # Use timeout command and store polling script in file to make easier to read
+  # Use timeout command and store polling logic in file to make it easier to read
   # Call bash shell explicitly since timeout uses "sh" shell by default, for some reason
+  # Also, we don't want to fail if we timeout in case the server *did* finish starting up but the script couldn't detect it due to a bug
+  # Effectively, this composite action is like calling "sleep" that is optimized to exit early when it detects an ok from the server
   - name: Wait for EE server to start
-    run: timeout 30 bash ./.github/workflows/wait-for-as-server-to-start.bash ${{ inputs.container-name }} ${{ inputs.is-security-enabled }}
+    run: timeout 5 bash ./.github/workflows/wait-for-as-server-to-start.bash ${{ inputs.container-name }} ${{ inputs.is-security-enabled }} || true
     shell: bash
