Reuse script in both GHA and entrypoint.sh

diff --git a/.github/actions/wait-for-as-server-to-start/action.yml b/.github/actions/wait-for-as-server-to-start/action.yml
--- a/.github/actions/wait-for-as-server-to-start/action.yml
+++ b/.github/actions/wait-for-as-server-to-start/action.yml
@@ -3,12 +3,7 @@ description: Only tested on Linux and macOS
 inputs:
   container-name:
     required: true
-  is-security-enabled:
-    required: false
-    default: 'false'
-  is-strong-consistency-enabled:
-    required: false
-    default: 'false'
+    description: Server container name
 
 runs:
   using: "composite"
@@ -18,11 +13,14 @@ runs:
     run: brew install coreutils
     shell: bash
 
-  # Composite actions doesn't support step-level timeout-minutes
-  # Use timeout command and store polling logic in file to make it easier to read
-  # Call bash shell explicitly since timeout uses "sh" shell by default, for some reason
-  # Also, we don't want to fail if we timeout in case the server *did* finish starting up but the script couldn't detect it due to a bug
-  # Effectively, this composite action is like calling "sleep" that is optimized to exit early when it detects an ok from the server
+  # * There is no healthcheck by default in the server Docker image,
+  # and we use the default image for community edition.
   - name: Wait for EE server to start
-    run: timeout 30 bash ./.github/workflows/wait-for-as-server-to-start.bash ${{ inputs.container-name }} ${{ inputs.is-security-enabled }} ${{ inputs.is-strong-consistency-enabled }} || true
+    # Composite actions doesn't support step-level timeout-minutes
+    # Use timeout command and store polling logic in file to make it easier to read
+    # Call bash shell explicitly since timeout uses "sh" shell by default, for some reason
+    # Also, we don't want to fail if we timeout in case the server *did* finish starting up but the script couldn't detect it due to a bug
+    # Effectively, this composite action is like calling "sleep" that is optimized to exit early when it detects an ok from the server
+    run: docker exec ${{ inputs.container-name }} timeout 30 bash wait-for-as-server-to-start.bash || true
+    working-directory: .github/workflows/docker-build-context
     shell: bash
