[CLIENT-2239] CI/CD: Run memory profiler test (#513)
* Allow pytest-memray to save dumps for tests with long names
* Ignore ZeroDivisionError thrown by pytest-memray

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -69,6 +69,45 @@ jobs:
         name: wheel-${{ matrix.py-version }}
         path: ./dist/*.whl
 
+  test-memray:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+
+    - uses: actions/setup-python@v2
+      with:
+        python-version: "3.8"
+        architecture: 'x64'
+
+    - uses: actions/download-artifact@v3
+      with:
+        name: wheel-3.8
+
+    - name: Install client
+      run: pip install *.whl
+
+    - name: Install test dependencies
+      run: pip install -r test/requirements.txt
+
+    - name: Run Aerospike server
+      run: docker run -d --name aerospike -p 3000-3002:3000-3002 aerospike/aerospike-server
+
+    - name: Wait for database to be ready
+      # Should be ready after 3 seconds
+      run: sleep 3
+
+    - name: Get number of tests
+      run: echo "NUM_TESTS=$(python3 -m pytest new_tests/ --collect-only -q | tail -n 1 | awk '{print $1;}')" >> $GITHUB_ENV
+      working-directory: test
+
+    - name: Run tests
+      # Get number of tests since setting to 0 doesn't work properly
+      # pytest-memray currently throws a ZeroDivision error due to having a bug
+      # We ignore this for now
+      run: python -m pytest ./new_tests --memray --memray-bin-path=./ --most-allocations=${{ env.NUM_TESTS }} || true
+      working-directory: test
+
   test-coverage:
     runs-on: ubuntu-latest
     steps:
